import json
from pathlib import Path
root=Path(r'C:\Users\ASUS\Documents\ChatGPT\Game')
run=root/'production/animation-remediation/miyabi/miyabi-remediation-20260906-r01'
rows=[]; levels=[0,0,1,2,2,1,0,0]
for i,level in enumerate(levels):
    rows.append({'specificationRevision':'miyabi-remediation-20260906-r01-sleep-cue-1','character':'hoshimi-miyabi','clip':'sleep_cue','frameId':f'frame-{i:03d}','timestampMs':i*150,'durationMs':150,'phase':'drowsiness','role':'hold' if i in [0,1,7] else 'breakdown','purpose':'restrained drowsiness cue without prop pop','identityReference':'assets/generated/pixel-chibi/production-v2/hoshimi-miyabi/layered-v6-clean/layers/miyabi-body-fixed.png','weaponReference':'assets/generated/pixel-chibi/production-v2/hoshimi-miyabi/hip-rise-crescent-slash-v3/references/weapon-overview.png','previousApprovedPose':'standing identity master','currentAnnotatedPoseGuide':'04-frame-specs/pose-guides/sleep-cue-frame-004-guide.png','nextApprovedPose':'standing identity master','previousPose':'standing body/weapon/feet fixed','currentPose':{'body':'identity master unchanged','eyelidLevel':level,'earTipReductionPixels':3 if level==2 else 0},'nextPose':'standing destination','landmarks':{k:{'previousXY':'identity-master-fixed','currentXY':'identity-master-fixed','nextXY':'identity-master-fixed','deltaXY':[0,0],'rotationChange':0,'fixedOrMoving':'fixed'} for k in ['head','shoulders','elbows','wrists','pelvis','knees','heels','toes','weaponHilt','weaponTip','propCompanionAnchor']},'weightAndBalance':'standing; no translation','support':'both feet on y=143','actionLine':'contained standing drowsiness','primaryMotion':'eyelid closure/recovery','weaponPropTrajectory':'none; weapon fixed','accelerationDeceleration':'hold then close then recover','secondaryMotion':'ear-tip reduction only at level 2','secondaryOnsetDelayMs':0,'silhouetteExpectation':'identity silhouette unchanged except 1px ear-tip softening','identityLocks':['body scale fixed','weapon fixed','feet baseline fixed','palette fixed'],'canvas':'160x144','placementAnchorXY':[64,120],'groundLineY':143,'authoredDirection':'right','mirrorRule':'runtime mirrors right','mustRemainUnchanged':['behavior semantics','clip duration','Firefly','food/effect policy'],'mustNotBeInvented':['Z symbol','food','plate','tea','slash','breath effect','new prop'],'outputRequirements':['RGBA PNG 160x144','transparent background','hard pixel edges','no annotation'],'status':'CANDIDATE_SOURCE_SPEC_USER_APPROVAL_PENDING'})
out={'run':'miyabi-remediation-20260906-r01','status':'CANDIDATE_SOURCE_SPEC_USER_APPROVAL_PENDING','rows':rows}
(run/'04-frame-specs/sleep-cue-source-spec.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(run/'04-frame-specs/sleep-cue-source-spec.json')
